export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEMS'
export const DELETE_FILE = 'DELETE_FILE'
export const ITEMS_LOADING = 'ITEMS_LOADING'
export const UPLOAD_ITEM = 'UPLOAD_ITEM'